### PR TITLE
Clean read_fed.f90 and setupfed.f90

### PR DESCRIPTION
**Pull request by hu5970**
remove unused variables found by DEBUG mode.
Merged changes from Hongli's test

### CODE REVIEW

**Review by hongli-wang — COMMENTED** [review]
missing lon or lat values in read_fed will cause crash. Please consider adding the below check after #404: 
           if(dlon_earth>=r360 .or. dlat_earth >90.0_r_kind) cycle

**Comment by hu5970** [comment]
@hongli-wang  read_fed.f90 line 212 has similar check. Could you check?

**Comment by hongli-wang** [comment]
> @hongli-wang read_fed.f90 line 212 has similar check. Could you check?

@hu5970 
I checked out your branch and had a test.  The line 212 will work for the fedbufr data. But now,  GSI reads in the NetCDF data. 
So similar check is required when the NetCDF file includes missing values. Amanda updated her code, the NetCDF file shouldn't have the missing lon/lat in future. 

You may change 90 to r90 for the line #208.

**Comment by hu5970** [comment]
@hongli-wang Which line I should add "if(dlon_earth>=r360 .or. dlat_earth >90.0_r_kind) cycle"?

**Comment by hongli-wang** [comment]
> @hongli-wang read_fed.f90 line 212 has similar check. Could you check?

@hu5970 Line #404, just after adjustment for long. It is like: 

           if(dlon_earth>=r360) dlon_earth=dlon_earth-r360
           if(dlon_earth<zero ) dlon_earth=dlon_earth+r360
           if(dlon_earth>=r360 .or. dlat_earth >90.0_r_kind) cycle

**Comment by hongli-wang** [comment]
> @hongli-wang Which line I should add "if(dlon_earth>=r360 .or. dlat_earth >90.0_r_kind) cycle"?

@hu5970 Line https://github.com/NOAA-EMC/GSI/pull/404, just after adjustment for long. It is like:

       if(dlon_earth>=r360) dlon_earth=dlon_earth-r360
       if(dlon_earth<zero ) dlon_earth=dlon_earth+r360
       if(dlon_earth>=r360 .or. dlat_earth >90.0_r_kind) cycle

**Comment by hu5970** [comment]
@hongli-wang Added. Please check.

**Comment by hongli-wang** [comment]
> @hongli-wang Added. Please check.

@hu5970 Looks good to me. Thanks!

**Review by daviddowellNOAA — APPROVED** [review]
Thanks @hu5970.  The proposed changes look good.  The modifications to read_fed.f90 remove unused variables and also add a helpful check for valid lat-lon values.  The changes to setupfed.f90 remove unused variables and also remove lines that were used for testing purposes but aren't actually needed for the new functionality. 

I compiled GSI with these changes and ran a test case of the GSI observer that includes FED observations.  The results are identical to those from runs of the test case with GSI before the current changes in this PR.

**Pull request merged**
